name: 'pdx_fresh_food'
version: '1.0.0'
config-version: 2

profile: 'pdx_fresh_food'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:         
  - "target"
  - "dbt_packages"
models:
  fresh_food_sources:
    example:
      materialized: table
  neighborhoods:
    example:
      materialized: table